@hostname = http://localhost:3000

@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzUzNDYzMTV9.c_Z1lL1E-WD5wa4ystMO-IxJYJj6rXqGijP5a-U4bk4

### Users create (signup)
POST {{ hostname }}/users
Content-Type:  application/json

{
  "name": "Test name",
  "email": "testname@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)

POST {{hostname}}/sessions
Content-Type: application/json

  {
    "email": "minnie@gmail.com",
    "password": "password"
  }

### Users show

GET {{ hostname }}/users/:id
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Users update
PATCH {{ hostname }}/users/:id
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "hours_away_per_day": 8,
  "dog_training_experience": "false"
}

### User destroy

DELETE {{ hostname }}/users/:id
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Favorites index

GET {{ hostname }}/favorites
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Favorites create
POST {{ hostname }}/favorites
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "api_dog_id": "55320928"
}

### Favorites delete
DELETE {{ hostname }}/favorites/2
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Breeds index
GET {{ hostname }}/breeds
Content-Type: application/json

### API Dog Index

GET {{ hostname }}/api_dogs
Content-Type: application/json
Authorization: Bearer {{jwt}}
